db:
  image: postgres
  ports:
  - "5432:5432"
  environment:
    POSTGRES_USER: test
    POSTGRES_PASSWORD: test
web:
  build: .
  links:
    - db
  environment: 
    SEQ_DB: test
    SEQ_USER: test
    SEQ_PW: test
    DATABASE_URL: postgres://username:test@db:5432
